In [54]:
from torchaudio.datasets import LIBRISPEECH
from torch.utils.data import DataLoader
import json
import pandas as pd
from pydub import AudioSegment
DATA_PATH = '/home/group6/Voice_Cloning/Mimik/Mimik_Voice_Cloner/ASR/datasets/LibriSpeech/'
TRAIN_DATA_PATH = DATA_PATH+'LibriSpeech_train_clean_100/'
TRAIN_DATA_JSON_PATH = '/home/group6/Voice_Cloning/Mimik/Mimik_Voice_Cloner/ASR/datasets/LibriSpeech_WAVS/train_clean_100/'
TEST_DATA_JSON_PATH = '/home/group6/Voice_Cloning/Mimik/Mimik_Voice_Cloner/ASR/datasets/LibriSpeech_WAVS/test_clean_100/'

In [55]:
ls_data = LIBRISPEECH(root = DATA_PATH, folder_in_archive='LibriSpeech_train_clean_100')
ls_data_loader = DataLoader(ls_data,1,shuffle=True)

In [35]:
round(len(ls_data)*0.005)

143

In [36]:
data_iter = ls_data_loader._get_iterator()
data_iter.__next__()

[tensor([[[ 4.5776e-04, -3.0518e-05, -2.5024e-03,  ..., -6.1035e-05,
           -6.1035e-05, -6.1035e-05]]]),
 tensor([16000]),
 ('AND THUS THAT CHURCH THOUGH AN EXPENSIVE AND BURDENSOME ESTABLISHMENT WAS LIABLE TO MANY OF THE INCONVENIENCES WHICH BELONG TO AN ORDER OF PRIESTS TRUSTING ENTIRELY TO THEIR OWN ART AND INVENTION FOR OBTAINING A SUBSISTENCE',),
 tensor([7635]),
 tensor([105661]),
 tensor([16])]

In [37]:
# def create_wav_from_flac(source_pth, dest_pth):
    

In [ ]:
temp_dict = dict.fromkeys(['Filepath','sample_rate','text','Speaker_ID', 'Chapter_ID', 'Utterance_ID'])
# temp_dict = sample_dict.copy()
train_data = {'Data':[]}
test_data = {'Data':[]}

for i, datapoint in enumerate(ls_data):
    if i > 200:break

    data = ls_data.get_metadata(i)
    
    if i%10 == 0:
            print('Processing file',i,'...\n')

    if i <= round(len(ls_data)*0.005):
        
        for j,key in enumerate(temp_dict.keys()):
            # print(key)
            if key == 'Filepath':
                audio_file = AudioSegment.from_file(TRAIN_DATA_PATH+data[j], format='flac')
                audio_file.set_channels(1)
                audio_file.export(f'{NEW_TRAIN_DATA_PATH}recording{i}.wav', format='wav')
                temp_dict.update([(key,f'{NEW_TRAIN_DATA_PATH}recording{i}.wav')])
            elif key == 'text':
                temp_dict.update([(key,data[j].lower())])
            else:
                temp_dict.update([(key,data[j])])
        train_data['Data'].append(temp_dict.copy())

    else:
        for j,key in enumerate(temp_dict.keys()):
            # print(key)
            if key == 'Filepath':
                audio_file = AudioSegment.from_file(TRAIN_DATA_PATH+data[j], format='flac')
                audio_file.set_channels(1)
                audio_file.export(f'{NEW_TEST_DATA_PATH}recording{i}.wav', format='wav')
                temp_dict.update([(key,f'{NEW_TEST_DATA_PATH}recording{i}.wav')])
            elif key == 'text':
                temp_dict.update([(key,data[j].lower())])
            else:
                temp_dict.update([(key,data[j])])
        test_data['Data'].append(temp_dict.copy())

        
# train_df = pd.DataFrame(train_data['Data'])
with open(NEW_TRAIN_DATA_PATH+'train_tc100.json','w') as file:
    json.dump(train_data['Data'],file, indent=1)
    file.close()

with open(NEW_TEST_DATA_PATH+'test_tc100.json','w') as file:
    json.dump(test_data['Data'],file, indent=1)
    file.close()

In [ ]:
temp_dict = dict.fromkeys(['Filepath','sample_rate','text','Speaker_ID', 'Chapter_ID', 'Utterance_ID'])
# temp_dict = sample_dict.copy()
train_data = {'Data':[]}
test_data = {'Data':[]}

for i, datapoint in enumerate(ls_data):
    if i > 50:break

    data = ls_data.get_metadata(i)
    
    if i%10 == 0:
            print('Processing file',i,'...\n')

    if i <= round(len(ls_data)*0.005):
        
        for j,key in enumerate(temp_dict.keys()):
            # print(key)
            if key == 'Filepath':
                temp_dict.update([(key,f'{DATA_PATH}recording{i}.wav')])
            elif key == 'text':
                temp_dict.update([(key,data[j].lower())])
            else:
                temp_dict.update([(key,data[j])])
        train_data['Data'].append(temp_dict.copy())

    else:
        for j,key in enumerate(temp_dict.keys()):
            # print(key)
            if key == 'Filepath':
                temp_dict.update([(key,f'{DATA_PATH}recording{i}.wav')])
            elif key == 'text':
                temp_dict.update([(key,data[j].lower())])
            else:
                temp_dict.update([(key,data[j])])
        test_data['Data'].append(temp_dict.copy())

        
# train_df = pd.DataFrame(train_data['Data'])
# with open(NEW_TRAIN_DATA_PATH+'train_tc100.json','w') as file:
#     json.dump(train_data['Data'],file, indent=1)
#     file.close()

# with open(NEW_TEST_DATA_PATH+'test_tc100.json','w') as file:
#     json.dump(test_data['Data'],file, indent=1)
#     file.close()


In [61]:
print(*train_data['Data'])

{'Filepath': '/home/group6/Voice_Cloning/Mimik/Mimik_Voice_Cloner/ASR/datasets/LibriSpeech/recording0.wav', 'sample_rate': 16000, 'text': 'chapter one missus rachel lynde is surprised missus rachel lynde lived just where the avonlea main road dipped down into a little hollow fringed with alders and ladies eardrops and traversed by a brook', 'Speaker_ID': 103, 'Chapter_ID': 1240, 'Utterance_ID': 0} {'Filepath': '/home/group6/Voice_Cloning/Mimik/Mimik_Voice_Cloner/ASR/datasets/LibriSpeech/recording1.wav', 'sample_rate': 16000, 'text': "that had its source away back in the woods of the old cuthbert place it was reputed to be an intricate headlong brook in its earlier course through those woods with dark secrets of pool and cascade but by the time it reached lynde's hollow it was a quiet well conducted little stream", 'Speaker_ID': 103, 'Chapter_ID': 1240, 'Utterance_ID': 1} {'Filepath': '/home/group6/Voice_Cloning/Mimik/Mimik_Voice_Cloner/ASR/datasets/LibriSpeech/recording2.wav', 'sample_

In [39]:
import librosa
import IPython.display as ipd

In [50]:
# audio = librosa.load('/home/group6/Voice_Cloning/Mimik/Mimik_Voice_Cloner/ASR/datasets/LibriSpeech_WAVS/train_clean_100/recording0.wav', sr=16000)
try:
    audio, sr = librosa.load('/home/group6/Voice_Cloning/Mimik/Mimik_Voice_Cloner/ASR/datasets/LibriSpeech_WAVS/train_clean_100/recording0.wav')
    audio_obj = ipd.Audio(data=audio, rate=sr)
    print(audio.shape,sr)
except Exception as e:
    print('ERROR:', e)

(310575,) 22050
