In [188]:
from torchaudio.datasets import LIBRISPEECH
from torch.utils.data import DataLoader
import json
import pandas as pd
DATA_PATH = '/home/group6/Voice_Cloning/Mimik/Mimik_Voice_Cloner/ASR/datasets/LibriSpeech/'

In [115]:
ls_data = LIBRISPEECH(root = DATA_PATH, folder_in_archive='LibriSpeech_train_clean_100')

ls_data_loader = DataLoader(ls_data,1,shuffle=True)

In [116]:
len(ls_data_loader)

28539

In [117]:
data_iter = ls_data_loader._get_iterator()
data_iter.__next__()

[tensor([[[-0.0009, -0.0003,  0.0000,  ...,  0.0004,  0.0009,  0.0007]]]),
 tensor([16000]),
 ('AND BETH REPLIED THAT HIS MANNERS WERE SO LIKE THOSE OF THEIR COUSIN LOUISE THAT THE TWO OUGHT TO GET ALONG NICELY TOGETHER UNCLE JOHN LIKED HIS NIECES TO MAKE FRIENDS AND ENCOURAGED YOUNG MEN GENERALLY TO MEET THEM',),
 tensor([1447]),
 tensor([17506]),
 tensor([12])]

In [204]:
temp_dict = dict.fromkeys(['Filepath','sample_rate','text','Speaker_ID', 'Chapter_ID', 'Utterance_ID'])
# temp_dict = sample_dict.copy()
train_data = {'Data':[]}
for i, datapoint in enumerate(ls_data):
    if i >= 5: break
    # if not (i % 1): print(f'Sample {i}')

    data = ls_data.get_metadata(i)
    # print('DATA:',data)
    for j,key in enumerate(temp_dict.keys()):
        # print(key)
        if key == 'Filepath':
            temp_dict.update([(key,f'{DATA_PATH}LibriSpeech_train_clean_100/{data[j]}')])
        elif key == 'text':
            temp_dict.update([(key,data[j].lower())])
        else:
            temp_dict.update([(key,data[j])])
    
    # print(sample_dict)
    train_data['Data'].append(temp_dict.copy())

# train_df = pd.DataFrame(train_data['Data'])
with open(DATA_PATH+'train_tc100.json','w') as file:
    json.dump(train_data['Data'],file, indent=1)
    file.close()


In [158]:
loaded_json = None
with open(DATA_PATH+'train_tc100.json','r') as file:
    loaded_json = json.load(file)

loaded_json[0]

{'Filepath': '/home/group6/Voice_Cloning/Mimik/Mimik_Voice_Cloner/ASR/datasets/LibriSpeech//LibriSpeech_train_clean_100/train-clean-100/1116/137572/1116-137572-0008.flac',
 'sample_rate': 16000,
 'text': 'AND DISADVANTAGES WITH WHICH THE COUPLE ENTER MARRIAGE THESE TRAITS CANNOT BE CHANGED OVERNIGHT NOR IS IT NECESSARY OR AT ALL WISE THAT THEY SHOULD BE JOHN ATTRACTS MARY AND SHE APPEALS TO HIM BECAUSE THE PERSONALITY OF EACH ONE IS WHAT IT IS',
 'Speaker_ID': 1116,
 'Chapter_ID': 137572,
 'Utterance_ID': 8}

In [150]:
import os
import librosa
import torch
import IPython.display as ipd

In [218]:
waveform, sr= librosa.load(loaded_json[0]['Filepath'], sr=loaded_json[0]['sample_rate'], mono=True)
waveform_T = torch.tensor(waveform)

In [210]:
ipd.Audio(waveform, rate = sr)

In [219]:
print(waveform_T.dim())
print(waveform_T)

1
tensor([-3.4485e-03, -1.0132e-02, -8.5449e-04,  ..., -3.0518e-05,
        -6.1035e-05, -9.1553e-05])
